apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
data:
  database_url: mongodb-service
