apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: {{ .Values.mongodb.port }}
      targetPort: {{ .Values.mongodb.port }}
