apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
spec:
  selector:
    app: mongo-express
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.mongoExpress.port }}
      targetPort: {{ .Values.mongoExpress.port }}
      nodePort: {{ .Values.mongoExpress.nodePort }}
