apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.mongodb.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.mongodb.storage.size }}
