apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
data:
  mongo-root-username: {{ .Values.mongodb.credentials.username }}
  mongo-root-password: {{ .Values.mongodb.credentials.password }}
